baseURL = "https://www.rapatao.com/"
languageCode = "en-us"
title = "rapatao.com"
theme = "new-rapatao.com"
#theme = "rapatao.com"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 5
canonifyurls = true

#disqusShortname = "rapatao-com"
summary = 10

googleAnalytics = "G-LDJ57WEQPH"

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'pastie'
tabWidth = 2


[outputs]
home = ["html"]

#[params]
#enableCDN = false
#cssFiles = ["default"]
#jsFiles = ["default"]
#highlightjs = true
#highlightjsTheme = ""
#highlightjsLang = []
#viewMorePostsLink = "/posts/"
#readingTime = true
#imageStretch = ""
#removeBlur = false
#socialShare = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
#hideEmptyStats = true
#images = ["/images/avatar-pixel.gif"]

#[params.social]
#twitter = "@rapatao"

#[params.meta]
#description = "My personal website containing my resume and some insights I have related to the technology area."
#author = "Luiz H. Rapatão"
#favicon = true
#svg = true
#faviconVersion      = "1"
#msColor = "#ffffff"
#iOSColor = "#ffffff"

[params.header]
title = "rapatao.com"

[params.intro]
header = "Luiz H. Rapatão"
paragraph = "Senior Software Engineer"

[params.intro.pic]
src = "/images/avatar-pixel.gif"
alt = "Luiz H. Rapatão"

[params.recents]
postAmount = 3

#[params.footer]
#rssFooter = true
#socialFooter = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[social]
github = "rapatao"
twitter = "rapatao"
linkedin = "rapatao"
#medium = "rapatao"
instagram = "luizrapatao"
#skype = "rapatao"
email = "rapatao@rapatao.com"
calendly = "rapatao"

[languages]
[languages.en]
languagename = "English"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"
pre = "<i class='fa fa-newspaper-o'></i>"

[[languages.en.menu.main]]
name = "Resume"
weight = 5
url = "resume/"
pre = "<i class='fa fa-file-text-o'></i>"

[[languages.en.menu.main]]
name = "JSON Formatter & Minifier"
weight = 10
url = "json/"
pre = "<i class='fa fa-code'></i>"

[languages.pt]
languagename = "Português"

[[languages.pt.menu.main]]
name = "Blog"
weight = 2
url = "pt/posts/"
pre = "<i class='fa fa-newspaper-o'></i>"

[[languages.pt.menu.main]]
name = "Experiência"
weight = 5
url = "pt/resume/"
pre = "<i class='fa fa-file-text-o'></i>"

[[languages.pt.menu.main]]
name = "JSON Formatter & Minifier"
weight = 10
url = "pt/json/"
pre = "<i class='fa fa-code'></i>"

[privacy]
[privacy.GoogleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false

[params.Reaktions]
#script = "http://localhost:8080/reaktions.js"
script = "https://reaktions.rapatao.com/reaktions.js"
enabled = true
