name = "rapatao.com (1.0.0)"
license = "MIT"
licenselink = "https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/LICENSE.md"
description = "official rapatao.com theme"
homepage = "https://github.com/rapatao/rapatao.github.io/themes/new-rapatao.com"
tags = []
features = []
min_version = "v0.62.0/extended"

[author]
  name = "Luiz H. Rapatao"
  homepage = "https://www.rapatao.com"

