name: Website Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: git config --global user.email "do-not-reply@rapatao.com"
      - run: git config --global user.name "GH Actions Automated Deploy"

      - run: curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.70.0_Linux-64bit.deb

      - run: |
          pwd

          git submodule init
          git submodule update

          hugo -t hugo-coder

          cd public && git add --all
          pwd
          git commit -m "Publishing..."
          git push origin master

          git push "https://rapatao:${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git" HEAD:master --follow-tags
