name: Hugo Deployment

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.70.0_Linux-64bit.deb

      - run: |
          rm -rf public
          mkdir public
          git worktree prune
          rm -rf .git/worktrees/public/

          echo "Checking out gh-pages branch into public"
          git worktree add -B master public origin/master

          echo "Removing existing files"
          rm -rf public/*

          echo "Cloning theme"
          git submodule init
          git submodule sync

          echo "Generating site"
          hugo -t hugo-coder

      - run: |
          echo "Updating master branch"
          cd public && git add --all && git commit -m "Publishing to master (publish.sh)"
