name: Hugo Deployment

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.70.0_Linux-64bit.deb
      - run: rm -rf public
      - run: mkdir public
      - run: git worktree prune
      - run: rm -rf .git/worktrees/public/
      - run: git worktree add -B master public origin/master
      - run: rm -rf public/*
      - run: git submodule init
      - run: git submodule sync
      - run: hugo -t hugo-coder
      - run: cd public && git add --all && git commit -m "Publishing..."
