name: Website Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: git config --global user.email "do-not-reply@rapatao.com"
      - run: git config --global user.name "GH Actions Automated Deploy"

      - run: curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
      - run: sudo dpkg -i hugo_extended_0.74.3_Linux-64bit.deb

      - run: |
          pwd

          git submodule init
          git submodule update

          hugo --minify -t hugo-future-imperfect-slim

          cd public && git add --all
          pwd
          git commit -m "Publishing..."

          git push "https://rapatao:${{ secrets.GITHUB_TOKEN }}@github.com/rapatao/rapatao.github.io.git" HEAD:master --force

      - run: curl http://www.google.com/ping\?sitemap\=https://www.rapatao.com/sitemap.xml
      - run: curl http://www.google.com/ping\?sitemap\=https://www.rapatao.com/pt/sitemap.xml
      - run: curl http://www.google.com/ping\?sitemap\=https://www.rapatao.com/en/sitemap.xml
